### ISSUE TITLE
Add JST-Connector

### ISSUE THREAD

**Issue by ScatteredDrifter** [ScatteredDrifter/Quasar-67#1]
To support a wider range of 65% Boards we could likely add a breakout for **JST-Connectors**. 
Because some boards require special placements / positions we ought to find a **universal** or find a compromise. 

I will leave this open and hope for contribution from @manudergrohse

**Comment by manudergrohse** [comment]
hi, der echte M4NU hier. 
![IMG_1665](https://github.com/ScatteredDrifter/Quasar-67/assets/68914531/00c6bd80-e10b-4ebe-9966-34d4879a2879)
![IMG_1664](https://github.com/ScatteredDrifter/Quasar-67/assets/68914531/2b08c57f-dfc6-4682-9f7d-4f1998d10da5)

**Comment by ScatteredDrifter** [comment]
Thank you for the description. 
The proposed Connector will link the internal pcb with an unified daughterboard, right?
Hence I will make it an alternative you can solder and use if you like ?

**Comment by manudergrohse** [comment]
yes to both 👍
