### ISSUE TITLE
optional 65 Blocker 

### ISSUE THREAD

**Issue by ScatteredDrifter** [ScatteredDrifter/Quasar-67#2]
for a wider support of **cases** we could make the **65 Blocker** optional. 
This means adding **mousebites** so that one could cut those of if they insist to. 

We could also leave it out entirely, making support easier by decreasing the amount of work ( especially regarding the hazardous dust of pcbs) 

I would like your comment on it @Sturek

**Comment by Sturek** [comment]
I would just make a cutout in the PCB for the blocker. I don't think there is a relevant downside to having the cutout.

**Comment by ScatteredDrifter** [comment]
Yea thats likely the easiest solution especially because its not exposing users with possible dust and other hazardous operations. 

I will consider and imclude it in the next revision of this pcb, thankyou!
